### ISSUE TITLE
Loading kubeconfig throws flag redefined error

### ISSUE THREAD

**Issue by PradeepTammali** [kubernetes-sigs/kubebuilder#1306]
Hi, 
I am new to kubebuilder. I am trying to create secret by loading config file from .kube folder.
When I am trying to run controller it throws this Error. 

`/tmp/go-build063008529/b001/exe/main flag redefined: kubeconfig                                                                                                             E0112 15:22:13.380492   13205 runtime.go:76] Observed a panic: /tmp/go-build063008529/b001/exe/main flag redefined: kubeconfig                                              goroutine 171 [running]:                                                                                                                                                    k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1320440, 0xc00035b650)                                                                                                              /home/pradeep/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/runtime/runtime.go:74 +0xa3                                                k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)                                                                                                                     /home/pradeep/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/runtime/runtime.go:48 +0x82                                                panic(0x1320440, 0xc00035b650)                                                                                                                                                      /usr/lib/go-1.13/src/runtime/panic.go:679 +0x1b2                                                                                                                    flag.(*FlagSet).Var(0xc000094180, 0x16e4360, 0xc00035b610, 0x151d70a, 0xa, 0x1538835, 0x24)                                                                                         /usr/lib/go-1.13/src/flag/flag.go:848 +0x4ae                                                                                                                        flag.(*FlagSet).StringVar(...)                                                                                                                                                      /usr/lib/go-1.13/src/flag/flag.go:751                                                                                                                               flag.(*FlagSet).String(0xc000094180, 0x151d70a, 0xa, 0xc0002be700, 0x1a, 0x1538835, 0x24, 0xc0002559e0)                                                                             /usr/lib/go-1.13/src/flag/flag.go:764 +0xa0                                                                                                                         flag.String(...)                                                                                                                                                                    /usr/lib/go-1.13/src/flag/flag.go:771                                                                                                                               nsc/k8s/io/controllers.(*MapRTicketReconciler).Reconcile(0xc000438630, 0xc000041909, 0x3, 0xc0002559e0, 0x11, 0xc000387cd8, 0xc000344510, 0xc0001061b8, 0x16eadc0)                  /home/pradeep/CRDs/MapRTicket/controllers/maprticket_controller.go:65 +0x20d                                                                                        sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc000154900, 0x13d0120, 0xc0003e1180, 0x0)                                                   /home/pradeep/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:256 +0x162                                                     sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc000154900, 0x0)                                                                         /home/pradeep/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:232 +0xcb                                                      sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).worker(0xc000154900)                                                                                           /home/pradeep/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:211 +0x2b                                                      k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc00035b5b0)                                                                                                                   /home/pradeep/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:152 +0x5e                                                     k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc00035b5b0, 0x3b9aca00, 0x0, 0x1, 0xc0000ac1e0)                                                                                     /home/pradeep/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:153 +0xf8                                                     k8s.io/apimachinery/pkg/util/wait.Until(0xc00035b5b0, 0x3b9aca00, 0xc0000ac1e0)                                                                                                     /home/pradeep/go/pkg/mod/k8s.io/apimachinery@v0.0.0-20190913080033-27d36303b655/pkg/util/wait/wait.go:88 +0x4d                                                      created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1                                                                                         /home/pradeep/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.4.0/pkg/internal/controller/controller.go:193 +0x328                                                     panic: /tmp/go-build063008529/b001/exe/main flag redefined: kubeconfig [recovered]                                                                                                  panic: /tmp/go-build063008529/b001/exe/main flag redefined: kubeconfig                                                                                                                                                                                   
`

The code snippet I am using in my controller to create clientset is as following.
```
var kubeconfig *string
	if home := homedir.HomeDir(); home != "" {
		kubeconfig = flag.String("kubeconfig", filepath.Join(home, ".kube", "config"), "(optional) absolute path to the kubeconfig file")
	} else {
		kubeconfig = flag.String("kubeconfig", "", "absolute path to the kubeconfig file")
	}
	flag.Parse()
	log.Info("kubeconfig - loading kube config file to get the kube context is successfull.")

	config, err := clientcmd.BuildConfigFromFlags("", *kubeconfig)
	if err != nil {
		panic(err)
	}
	clientset, err := kubernetes.NewForConfig(config)
	if err != nil {
		panic(err)
	}
```

Can someone suggest what I am doing wrong. 
/triage support

**Comment by ylmcr7** [comment]
how soultuion ?
