### ISSUE TITLE
brew formula 2.3.0 upgrade issue

### ISSUE THREAD

**Issue by chenrui333** [kubernetes-sigs/kubebuilder#1421]
relates to https://github.com/Homebrew/homebrew-core/pull/51004

build failure:

```
go: downloading github.com/satori/go.uuid v1.2.0
go: found github.com/satori/go.uuid in github.com/satori/go.uuid v1.2.0
go: updating go.mod: existing contents have changed since last read
make: *** [vet] Error 1
make: *** Waiting for unfinished jobs....
2020/03/03 00:15:58 failed to initialize project: exit status 2
Error: kubebuilder: failed
```

/kind bug

**Comment by ndrpnt** [comment]
Hi, not sure what to look for, here is more info.

This runs fine (v2.2.0):
```
brew test kubebuilder -v

Testing kubebuilder
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200308-63772-1od8buc.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubebuilder.rb --verbose
==> /usr/local/Cellar/kubebuilder/2.2.0/bin/kubebuilder init --repo=github.com/example/example-repo --domain=example.com --license=apache2 --owner='The Example authors' --fetch-deps=false
Skipping fetching dependencies.
Next: Define a resource with:
$ kubebuilder create api
```

This fails (v2.3.0):
```
brew test kubebuilder -v

Testing kubebuilder
/usr/bin/sandbox-exec -f /private/tmp/homebrew20200308-60316-1euliol.sb ruby -W0 -I $LOAD_PATH -- /usr/local/Homebrew/Library/Homebrew/test.rb /usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubebuilder.rb --verbose
==> /usr/local/Cellar/kubebuilder/2.3.0/bin/kubebuilder init --repo=github.com/example/example-repo --domain=example.com --license=apache2 --owner='The Example authors' --fetch-deps=false
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.5.0
go: downloading sigs.k8s.io/controller-runtime v0.5.0
go: downloading k8s.io/apimachinery v0.17.2
go: downloading github.com/go-logr/logr v0.1.0
go: downloading k8s.io/client-go v0.17.2
go: downloading github.com/prometheus/client_golang v1.0.0
go: downloading k8s.io/api v0.17.2
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading github.com/beorn7/perks v1.0.0
go: downloading github.com/prometheus/procfs v0.0.2
go: downloading github.com/gogo/protobuf v1.2.2-0.20190723190241-65acae22fc9d
go: downloading github.com/evanphx/json-patch v4.5.0+incompatible
go: downloading k8s.io/apiextensions-apiserver v0.17.2
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading github.com/prometheus/common v0.4.1
go: downloading golang.org/x/crypto v0.0.0-20190820162420-60c769a6c586
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/imdario/mergo v0.3.6
go: downloading github.com/json-iterator/go v1.1.8
go: downloading github.com/golang/protobuf v1.3.2
go: downloading github.com/pkg/errors v0.8.1
go: downloading github.com/spf13/pflag v1.0.5
go: downloading k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
go: downloading github.com/modern-go/reflect2 v1.0.1
go: downloading github.com/google/uuid v1.1.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/google/gofuzz v1.0.0
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: downloading golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
go: downloading github.com/golang/groupcache v0.0.0-20180513044358-24b0969c4cb7
go: downloading gomodules.xyz/jsonpatch/v2 v2.0.1
go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
go: downloading github.com/googleapis/gnostic v0.3.1
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading k8s.io/kube-openapi v0.0.0-20191107075043-30be4d16710a
go: downloading sigs.k8s.io/yaml v1.1.0
go: downloading github.com/google/go-cmp v0.3.0
go: downloading gopkg.in/fsnotify.v1 v1.4.7
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading gopkg.in/yaml.v2 v2.2.4
go: downloading google.golang.org/appengine v1.5.0
go: downloading golang.org/x/text v0.3.2
Update go.mod:
$ go mod tidy
go: downloading go.uber.org/zap v1.10.0
go: downloading github.com/stretchr/testify v1.4.0
go: downloading github.com/go-logr/zapr v0.1.0
go: downloading github.com/onsi/ginkgo v1.11.0
go: downloading gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: downloading github.com/onsi/gomega v1.8.1
go: downloading cloud.google.com/go v0.38.0
go: downloading github.com/kr/pretty v0.1.0
go: downloading go.uber.org/multierr v1.1.0
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: downloading go.uber.org/atomic v1.3.2
go: downloading golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7
go: downloading github.com/kr/text v0.1.0
go: downloading github.com/hpcloud/tail v1.0.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
Running make:
$ make
/Users/julien.alexandre/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
go: finding module for package github.com/jessevdk/go-flags
go: finding module for package github.com/jessevdk/go-flags
go: finding module for package github.com/apex/log
go: finding module for package github.com/apex/log/handlers/json
go: finding module for package github.com/rs/zerolog
go: downloading github.com/sirupsen/logrus v1.4.2
go: downloading github.com/go-kit/kit v0.8.0
go: finding module for package go.pedge.io/lion
go: finding module for package gopkg.in/inconshreveable/log15.v2
go: downloading github.com/jessevdk/go-flags v1.4.0
go: downloading gopkg.in/inconshreveable/log15.v2 v2.0.0-20200109203555-b30bc20e4fd1
go: downloading github.com/jessevdk/go-flags v1.4.0
go: downloading github.com/rs/zerolog v1.18.0
go: downloading github.com/apex/log v1.1.2
go: downloading go.pedge.io/lion v0.0.0-20190619200210-304b2f426641
go: found github.com/jessevdk/go-flags in github.com/jessevdk/go-flags v1.4.0
go: downloading github.com/go-logfmt/logfmt v0.3.0
go: found github.com/jessevdk/go-flags in github.com/jessevdk/go-flags v1.4.0
go: found github.com/apex/log in github.com/apex/log v1.1.2
go: found github.com/rs/zerolog in github.com/rs/zerolog v1.18.0
go: found go.pedge.io/lion in go.pedge.io/lion v0.0.0-20190619200210-304b2f426641
go: found gopkg.in/inconshreveable/log15.v2 in gopkg.in/inconshreveable/log15.v2 v2.0.0-20200109203555-b30bc20e4fd1
go: not formatting packages in dependency modules
go: downloading github.com/go-logfmt/logfmt v0.4.0
go: downloading github.com/fatih/color v1.7.0
go: downloading github.com/mattn/go-isatty v0.0.8
go: downloading github.com/mattn/go-colorable v0.1.2
go: downloading github.com/go-stack/stack v1.8.0
go: finding module for package github.com/satori/go.uuid
go: downloading github.com/satori/go.uuid v1.2.0
go: found github.com/satori/go.uuid in github.com/satori/go.uuid v1.2.0
go: updating go.mod: existing contents have changed since last read
make: *** [vet] Error 1
2020/03/08 19:22:52 failed to initialize project: exit status 2
Error: kubebuilder: failed
Failed executing:
/usr/local/Homebrew/Library/Homebrew/formula.rb:1953:in `block in system'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1890:in `open'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1890:in `system'
/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core/Formula/kubebuilder.rb:27:in `block in <class:Kubebuilder>'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1760:in `block (3 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/utils.rb:478:in `with_env'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1759:in `block (2 levels) in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:865:in `with_logging'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1758:in `block in run_test'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2003:in `block in mktemp'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `block in run'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `chdir'
/usr/local/Homebrew/Library/Homebrew/mktemp.rb:57:in `run'
/usr/local/Homebrew/Library/Homebrew/formula.rb:2002:in `mktemp'
/usr/local/Homebrew/Library/Homebrew/formula.rb:1752:in `run_test'
/usr/local/Homebrew/Library/Homebrew/test.rb:33:in `block in <main>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:93:in `block in timeout'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `block in catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:33:in `catch'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/timeout.rb:108:in `timeout'
/usr/local/Homebrew/Library/Homebrew/test.rb:32:in `<main>'
```

This runs fine too (in docker):
```
docker run --rm golang:1.13 \
  bash -c "git clone https://github.com/kubernetes-sigs/kubebuilder.git --branch v2.3.0 --single-branch --depth 1 && \
  cd kubebuilder/ && \
  make build && \
  mv bin/kubebuilder /bin/ && \
  mkdir /work && \
  cd /work/ && \
  kubebuilder init --repo=github.com/example/example-repo --domain=example.com --license=apache2 --owner='The Example authors' --fetch-deps=false && \
  echo $?"

Cloning into 'kubebuilder'...
Note: checking out '800f63a7e41a6a8016d4cb9d583e1705b0812c9d'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

go build -o bin/kubebuilder ./cmd
go: downloading github.com/gobuffalo/flect v0.2.0
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/tools v0.0.0-20190920225731-5eefd052ad72
go: downloading github.com/spf13/cobra v0.0.5
go: downloading sigs.k8s.io/yaml v1.1.0
go: downloading github.com/spf13/afero v1.2.2
go: extracting sigs.k8s.io/yaml v1.1.0
go: downloading gopkg.in/yaml.v2 v2.2.4
go: extracting github.com/gobuffalo/flect v0.2.0
go: extracting github.com/spf13/pflag v1.0.5
go: extracting github.com/spf13/afero v1.2.2
go: extracting gopkg.in/yaml.v2 v2.2.4
go: extracting github.com/spf13/cobra v0.0.5
go: downloading golang.org/x/text v0.3.2
go: extracting golang.org/x/tools v0.0.0-20190920225731-5eefd052ad72
go: extracting golang.org/x/text v0.3.2
go: finding github.com/spf13/pflag v1.0.5
go: finding github.com/spf13/cobra v0.0.5
go: finding golang.org/x/tools v0.0.0-20190920225731-5eefd052ad72
go: finding github.com/gobuffalo/flect v0.2.0
go: finding sigs.k8s.io/yaml v1.1.0
go: finding github.com/spf13/afero v1.2.2
go: finding gopkg.in/yaml.v2 v2.2.4
go: finding golang.org/x/text v0.3.2
Writing scaffold for you to edit...
Get controller runtime:
$ go get sigs.k8s.io/controller-runtime@v0.5.0
go: finding sigs.k8s.io/controller-runtime v0.5.0
go: downloading sigs.k8s.io/controller-runtime v0.5.0
go: extracting sigs.k8s.io/controller-runtime v0.5.0
go: downloading k8s.io/apimachinery v0.17.2
go: downloading k8s.io/client-go v0.17.2
go: downloading github.com/evanphx/json-patch v4.5.0+incompatible
go: downloading github.com/go-logr/logr v0.1.0
go: extracting github.com/evanphx/json-patch v4.5.0+incompatible
go: extracting github.com/go-logr/logr v0.1.0
go: extracting k8s.io/apimachinery v0.17.2
go: extracting k8s.io/client-go v0.17.2
go: downloading github.com/prometheus/client_golang v1.0.0
go: downloading github.com/gogo/protobuf v1.2.2-0.20190723190241-65acae22fc9d
go: extracting github.com/prometheus/client_golang v1.0.0
go: downloading gomodules.xyz/jsonpatch/v2 v2.0.1
go: downloading github.com/pkg/errors v0.8.1
go: extracting gomodules.xyz/jsonpatch/v2 v2.0.1
go: extracting github.com/pkg/errors v0.8.1
go: downloading github.com/beorn7/perks v1.0.0
go: extracting github.com/beorn7/perks v1.0.0
go: downloading github.com/prometheus/common v0.4.1
go: downloading github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: extracting github.com/prometheus/common v0.4.1
go: downloading github.com/golang/protobuf v1.3.2
go: downloading k8s.io/api v0.17.2
go: extracting github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: downloading k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
go: extracting github.com/golang/protobuf v1.3.2
go: extracting k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
go: extracting github.com/gogo/protobuf v1.2.2-0.20190723190241-65acae22fc9d
go: downloading golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
go: extracting k8s.io/api v0.17.2
go: extracting golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
go: downloading k8s.io/klog v1.0.0
go: downloading github.com/hashicorp/golang-lru v0.5.1
go: downloading golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
go: downloading github.com/json-iterator/go v1.1.8
go: downloading github.com/prometheus/procfs v0.0.2
go: downloading github.com/googleapis/gnostic v0.3.1
go: downloading k8s.io/apiextensions-apiserver v0.17.2
go: downloading github.com/imdario/mergo v0.3.6
go: extracting github.com/hashicorp/golang-lru v0.5.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: extracting k8s.io/klog v1.0.0
go: downloading github.com/google/gofuzz v1.0.0
go: downloading golang.org/x/crypto v0.0.0-20190820162420-60c769a6c586
go: extracting github.com/json-iterator/go v1.1.8
go: extracting github.com/prometheus/procfs v0.0.2
go: downloading gopkg.in/inf.v0 v0.9.1
go: downloading golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: extracting github.com/imdario/mergo v0.3.6
go: downloading github.com/golang/groupcache v0.0.0-20180513044358-24b0969c4cb7
go: extracting github.com/davecgh/go-spew v1.1.1
go: downloading github.com/modern-go/reflect2 v1.0.1
go: extracting github.com/google/gofuzz v1.0.0
go: downloading github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: extracting k8s.io/apiextensions-apiserver v0.17.2
go: extracting github.com/googleapis/gnostic v0.3.1
go: extracting gopkg.in/inf.v0 v0.9.1
go: extracting golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: downloading golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: extracting github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: extracting golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: downloading k8s.io/kube-openapi v0.0.0-20191107075043-30be4d16710a
go: extracting github.com/modern-go/reflect2 v1.0.1
go: downloading gopkg.in/fsnotify.v1 v1.4.7
go: downloading github.com/google/go-cmp v0.3.0
go: downloading google.golang.org/appengine v1.5.0
go: extracting github.com/golang/groupcache v0.0.0-20180513044358-24b0969c4cb7
go: extracting github.com/matttproud/golang_protobuf_extensions v1.0.1
go: downloading github.com/google/uuid v1.1.1
go: extracting gopkg.in/fsnotify.v1 v1.4.7
go: extracting github.com/google/go-cmp v0.3.0
go: extracting github.com/google/uuid v1.1.1
go: extracting golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
go: extracting golang.org/x/crypto v0.0.0-20190820162420-60c769a6c586
go: extracting google.golang.org/appengine v1.5.0
go: extracting k8s.io/kube-openapi v0.0.0-20191107075043-30be4d16710a
go: finding github.com/go-logr/logr v0.1.0
go: finding k8s.io/apimachinery v0.17.2
go: finding k8s.io/client-go v0.17.2
go: finding github.com/prometheus/client_golang v1.0.0
go: finding github.com/gogo/protobuf v1.2.2-0.20190723190241-65acae22fc9d
go: finding k8s.io/api v0.17.2
go: finding gopkg.in/inf.v0 v0.9.1
go: finding github.com/imdario/mergo v0.3.6
go: finding github.com/google/gofuzz v1.0.0
go: finding golang.org/x/time v0.0.0-20190308202827-9d24e82272b4
go: finding golang.org/x/crypto v0.0.0-20190820162420-60c769a6c586
go: finding github.com/evanphx/json-patch v4.5.0+incompatible
go: finding golang.org/x/net v0.0.0-20191004110552-13f9640d40b9
go: finding github.com/prometheus/client_model v0.0.0-20190129233127-fd36f4220a90
go: finding k8s.io/klog v1.0.0
go: finding github.com/prometheus/common v0.4.1
go: finding github.com/golang/groupcache v0.0.0-20180513044358-24b0969c4cb7
go: finding github.com/pkg/errors v0.8.1
go: finding golang.org/x/sys v0.0.0-20190826190057-c7b8b68b1456
go: finding github.com/golang/protobuf v1.3.2
go: finding github.com/beorn7/perks v1.0.0
go: finding k8s.io/apiextensions-apiserver v0.17.2
go: finding github.com/googleapis/gnostic v0.3.1
go: finding gomodules.xyz/jsonpatch/v2 v2.0.1
go: finding github.com/json-iterator/go v1.1.8
go: finding github.com/matttproud/golang_protobuf_extensions v1.0.1
go: finding github.com/modern-go/reflect2 v1.0.1
go: finding github.com/prometheus/procfs v0.0.2
go: finding github.com/google/uuid v1.1.1
go: finding github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd
go: finding github.com/davecgh/go-spew v1.1.1
go: finding k8s.io/kube-openapi v0.0.0-20191107075043-30be4d16710a
go: finding k8s.io/utils v0.0.0-20191114184206-e782cd3c129f
go: finding golang.org/x/oauth2 v0.0.0-20190604053449-0f29369cfe45
go: finding gopkg.in/fsnotify.v1 v1.4.7
go: finding github.com/hashicorp/golang-lru v0.5.1
go: finding github.com/google/go-cmp v0.3.0
Update go.mod:
$ go mod tidy
go: downloading github.com/go-logr/zapr v0.1.0
go: downloading go.uber.org/zap v1.10.0
go: downloading github.com/onsi/ginkgo v1.11.0
go: downloading github.com/onsi/gomega v1.8.1
go: downloading github.com/stretchr/testify v1.4.0
go: extracting github.com/go-logr/zapr v0.1.0
go: downloading gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: extracting github.com/onsi/ginkgo v1.11.0
go: extracting github.com/stretchr/testify v1.4.0
go: extracting github.com/onsi/gomega v1.8.1
go: extracting gopkg.in/check.v1 v1.0.0-20180628173108-788fd7840127
go: extracting go.uber.org/zap v1.10.0
go: downloading github.com/pmezard/go-difflib v1.0.0
go: downloading cloud.google.com/go v0.38.0
go: downloading github.com/kr/pretty v0.1.0
go: extracting github.com/pmezard/go-difflib v1.0.0
go: downloading go.uber.org/atomic v1.3.2
go: downloading go.uber.org/multierr v1.1.0
go: downloading golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7
go: extracting github.com/kr/pretty v0.1.0
go: downloading github.com/kr/text v0.1.0
go: extracting go.uber.org/atomic v1.3.2
go: extracting go.uber.org/multierr v1.1.0
go: extracting golang.org/x/xerrors v0.0.0-20190717185122-a985d3407aa7
go: extracting github.com/kr/text v0.1.0
go: downloading github.com/hpcloud/tail v1.0.0
go: downloading github.com/fsnotify/fsnotify v1.4.7
go: extracting github.com/fsnotify/fsnotify v1.4.7
go: extracting github.com/hpcloud/tail v1.0.0
go: downloading gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: extracting gopkg.in/tomb.v1 v1.0.0-20141024135613-dd632973f1e7
go: extracting cloud.google.com/go v0.38.0
Running make:
$ make
go: creating new go.mod: module tmp
go: finding sigs.k8s.io/controller-tools v0.2.5
go: finding sigs.k8s.io/controller-tools/cmd v0.2.5
go: finding sigs.k8s.io v0.2.5
go: finding sigs.k8s.io/controller-tools/cmd/controller-gen v0.2.5
go: downloading sigs.k8s.io/controller-tools v0.2.5
go: extracting sigs.k8s.io/controller-tools v0.2.5
go: downloading gopkg.in/yaml.v3 v3.0.0-20190905181640-827449938966
go: downloading github.com/fatih/color v1.7.0
go: downloading k8s.io/apimachinery v0.17.0
go: downloading k8s.io/apiextensions-apiserver v0.17.0
go: downloading k8s.io/api v0.17.0
go: extracting github.com/fatih/color v1.7.0
go: downloading github.com/inconshreveable/mousetrap v1.0.0
go: extracting gopkg.in/yaml.v3 v3.0.0-20190905181640-827449938966
go: downloading github.com/mattn/go-isatty v0.0.8
go: extracting github.com/mattn/go-isatty v0.0.8
go: extracting github.com/inconshreveable/mousetrap v1.0.0
go: downloading github.com/mattn/go-colorable v0.1.2
go: extracting k8s.io/apimachinery v0.17.0
go: extracting github.com/mattn/go-colorable v0.1.2
go: extracting k8s.io/apiextensions-apiserver v0.17.0
go: extracting k8s.io/api v0.17.0
go: finding k8s.io/apiextensions-apiserver v0.17.0
go: finding github.com/fatih/color v1.7.0
go: finding k8s.io/api v0.17.0
go: finding gopkg.in/yaml.v3 v3.0.0-20190905181640-827449938966
go: finding k8s.io/apimachinery v0.17.0
go: finding github.com/mattn/go-colorable v0.1.2
go: finding github.com/mattn/go-isatty v0.0.8
/go/bin/controller-gen object:headerFile="hack/boilerplate.go.txt" paths="./..."
go fmt ./...
go vet ./...
go build -o bin/manager main.go
Next: define a resource with:
$ kubebuilder create api
0
```

**Comment by Adirio** [comment]
Could you please add the following information to each of the cases:

- go version
- kubebuilder version (`kubebuilder version`)
- scaffolding version (check your `PROJECT` file)
- controller-runtime version (check your `go.mod` file)
- controller-tools version
- Kubernetes & kubectl versions (just run `kubectl version` against your API server)

**Comment by ndrpnt** [comment]
In order:

```
- go version: 1.14
- kubebuilder version: v2.2.0
- scaffolding version: 2
- controller-runtime version: not downloading it
- controller-tools version: v0.2.1 (already present on host)
- kubectl version: v1.17.3
```

```
- go version: 1.14
- kubebuilder version: v2.3.0
- scaffolding version: 2
- controller-runtime version: v0.5.0
- controller-tools version: v0.2.1 and v0.2.5 (tested with both)
- kubectl version: v1.17.3
```

```
- go version: 1.13.8
- kubebuilder version: v2.3.0
- scaffolding version: 2
- controller-runtime version: v0.5.0
- controller-tools version: v0.2.5
- kubectl version: none
```

It seems that `--fetch-deps=false` is ignored with version `v2.3.0` which is breaking homebrew's tests

**Comment by chenrui333** [comment]
Bump the PR to the latest release, v2.3.1 
https://github.com/Homebrew/homebrew-core/pull/52196

**Comment by camilamacedo86** [comment]
I did the test to check it with the latest version. Following the steps.
- rm -rf the local bin
- use brew to install it `brew install kubebuilder`
- then, run  brew test kubebuilder -v

All worked successfully with kubebuilder 2.3.1. So, I am closing this one. However, feel to re-open if you see that something still required to get done here. 

/close
