### ISSUE TITLE
Testsuite fails to start up control plane

### ISSUE THREAD

**Issue by jabbrwcky** [kubernetes-sigs/kubebuilder#1463]
I am currently using kubebuilder 2.2.0 and the controller test_suite does run into timeouts when starting the control-plane most of the time (dev running on OSX Catalina FWIW).

I had issues with running out of file descriptors (OSX Catalina defaults to 256 soft limt), which I could raise and resolve this.

Still the control-plane startup runs for some time and eventually stops working, without any changes to the test suite code. If the tests run, the controller suite currently runs for about 11 seconds and uses the default timeout of 60 seconds for starting up the suite.

This is quite a puzzler and a huge timesink :(

So I increased the log verbosity and I could find a failing health check as propable reason for the startup failure:

```
I0407 09:38:17.780721    8559 handler.go:153] kube-aggregator: GET "/healthz" satisfied by nonGoRestful
I0407 09:38:17.780740    8559 pathrecorder.go:240] kube-aggregator: "/healthz" satisfied by exact match
I0407 09:38:17.781227    8559 healthz.go:161] healthz check poststarthook/crd-informer-synced failed: not finished
I0407 09:38:17.781246    8559 healthz.go:161] healthz check poststarthook/bootstrap-controller failed: not finished
I0407 09:38:17.781255    8559 healthz.go:161] healthz check poststarthook/scheduling/bootstrap-system-priority-classes failed: not finished
I0407 09:38:17.781263    8559 healthz.go:161] healthz check poststarthook/ca-registration failed: not finished
I0407 09:38:17.781302    8559 healthz.go:161] healthz check autoregister-completion failed: missing APIService: [v1. v1.apps v1.authentication.k8s.io v1.authorization.k8s.io v1.autoscaling v1.batch v1.coordination.k8s.io v1.networking.k8s.io v1.rbac.authorization.k8s.io v1.scheduling.k8s.io v1.storage.k8s.io v1beta1.admissionregistration.k8s.io v1beta1.apiextensions.k8s.io v1beta1.apps v1beta1.authentication.k8s.io v1beta1.authorization.k8s.io v1beta1.batch v1beta1.certificates.k8s.io v1beta1.coordination.k8s.io v1beta1.events.k8s.io v1beta1.extensions v1beta1.networking.k8s.io v1beta1.node.k8s.io v1beta1.policy v1beta1.rbac.authorization.k8s.io v1beta1.scheduling.k8s.io v1beta1.storage.k8s.io v1beta2.apps v2beta1.autoscaling v2beta2.autoscaling]
I0407 09:38:17.781318    8559 healthz.go:175] [+]ping ok
[+]log ok
[+]etcd ok
[+]poststarthook/generic-apiserver-start-informers ok
[+]poststarthook/start-apiextensions-informers ok
[+]poststarthook/start-apiextensions-controllers ok
[-]poststarthook/crd-informer-synced failed: reason withheld
[-]poststarthook/bootstrap-controller failed: reason withheld
[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: reason withheld
[-]poststarthook/ca-registration failed: reason withheld
[+]poststarthook/start-kube-apiserver-admission-initializer ok
[+]poststarthook/start-kube-aggregator-informers ok
[+]poststarthook/apiservice-registration-controller ok
[+]poststarthook/apiservice-status-available-controller ok
[+]poststarthook/apiservice-openapi-controller ok
[+]poststarthook/kube-apiserver-autoregistration ok
[-]autoregister-completion failed: reason withheld
healthz check failed
I0407 09:38:17.781428    8559 wrap.go:47] GET /healthz: (750.902µs) 500
goroutine 2954 [running]:
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).recordStatus(0xc003d43e30, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:204 +0xc8
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog.(*respLogger).WriteHeader(0xc003d43e30, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/httplog/httplog.go:183 +0x35
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*baseTimeoutWriter).WriteHeader(0xc00537e7a0, 0x1f4)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:227 +0xa6
net/http.Error(0xf5f4700, 0xc00073f668, 0xc0080dbc00, 0x358, 0x1f4)
	/usr/local/go/src/net/http/server.go:2007 +0x213
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz.handleRootHealthz.func1(0xf5f4700, 0xc00073f668, 0xc00804ab00)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go:176 +0x43d
net/http.HandlerFunc.ServeHTTP(0xc00693c020, 0xf5f4700, 0xc00073f668, 0xc00804ab00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*pathHandler).ServeHTTP(0xc007bc1040, 0xf5f4700, 0xc00073f668, 0xc00804ab00)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:241 +0x548
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux.(*PathRecorderMux).ServeHTTP(0xc0014d4000, 0xf5f4700, 0xc00073f668, 0xc00804ab00)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/mux/pathrecorder.go:234 +0x85
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server.director.ServeHTTP(0x4eee85b, 0xf, 0xc0041e23f0, 0xc0014d4000, 0xf5f4700, 0xc00073f668, 0xc00804ab00)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/handler.go:154 +0x6c3
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters.WithAuthentication.func1(0xf5f4700, 0xc00073f668, 0xc00804aa00)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/endpoints/filters/authentication.go:81 +0x527
net/http.HandlerFunc.ServeHTTP(0xc004082460, 0xf5f4700, 0xc00073f668, 0xc00804aa00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP.func1(0xc006c1f3e0, 0xc00575d120, 0x7fb0920, 0xc00073f668, 0xc00804aa00)
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:112 +0xb3
created by k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters.(*timeoutHandler).ServeHTTP
	/go/src/k8s.io/kubernetes/_output/local/go/src/k8s.io/kubernetes/vendor/k8s.io/apiserver/pkg/server/filters/timeout.go:99 +0x1b1

logging error output: "[+]ping ok\n[+]log ok\n[+]etcd ok\n[+]poststarthook/generic-apiserver-start-informers ok\n[+]poststarthook/start-apiextensions-informers ok\n[+]poststarthook/start-apiextensions-controllers ok\n[-]poststarthook/crd-informer-synced failed: reason withheld\n[-]poststarthook/bootstrap-controller failed: reason withheld\n[-]poststarthook/scheduling/bootstrap-system-priority-classes failed: reason withheld\n[-]poststarthook/ca-registration failed: reason withheld\n[+]poststarthook/start-kube-apiserver-admission-initializer ok\n[+]poststarthook/start-kube-aggregator-informers ok\n[+]poststarthook/apiservice-registration-controller ok\n[+]poststarthook/apiservice-status-available-controller ok\n[+]poststarthook/apiservice-openapi-controller ok\n[+]poststarthook/kube-apiserver-autoregistration ok\n[-]autoregister-completion failed: reason withheld\nhealthz check failed\n"
 [Go-http-client/1.1 127.0.0.1:63628]
```

I have to admit that I do not have any idea why it fails and how to fix it. Maybe someone has had this issue in the past and ther eis a simple solution for that.

Curent envtest configuration is:

```go
	testEnv = &envtest.Environment{
		CRDDirectoryPaths:        []string{filepath.Join("..", "config", "crd", "bases")},
		AttachControlPlaneOutput: true,
		KubeAPIServerFlags: []string{
			"--bind-address=127.0.0.1",
			"--advertise-address=127.0.0.1",
			"--etcd-servers={{ if .EtcdURL }}{{ .EtcdURL.String }}{{ end }}",
			"--cert-dir={{ .CertDir }}",
			"--insecure-port={{ if .URL }}{{ .URL.Port }}{{ end }}",
			"--insecure-bind-address={{ if .URL }}{{ .URL.Hostname }}{{ end }}",
			"-v=5",
			"--secure-port={{ if .SecurePort }}{{ .SecurePort }}{{ end }}",
			"--service-cluster-ip-range=10.0.0.0/24",
			"--enable-admission-plugins=AlwaysAdmit"},
	}
```

**Comment by jabbrwcky** [comment]
Somehow the go.mod file had a different apimachinery version than the one generated by vanilla kubebuilder 2.2.0 - resetting this mostly fixed it - I got one failure since.

Could specifying `"--bind-address=127.0.0.1"` have an impact on this?

**Comment by jabbrwcky** [comment]
Ok, I did some testing.

The default configuration fails for me reproducably and the test runs into timeouts.

```go
testEnv = &envtest.Environment{
	CRDDirectoryPaths:  []string{filepath.Join("..", "config", "crd", "bases")},
}
```

Specifiying a binding address explicitly makes the tests run reproducibly:

```go
testEnv = &envtest.Environment{
	CRDDirectoryPaths:  []string{filepath.Join("..", "config", "crd", "bases")},
	KubeAPIServerFlags: append(envtest.DefaultKubeAPIServerFlags, "--bind-address=127.0.0.1"),
}
```

**Comment by dpaclt** [comment]
Were you able to fix this error ?
