### ISSUE TITLE
Book theme not loading correctly for newly accessed users

### ISSUE THREAD

**Issue by rytswd** [kubernetes-sigs/kubebuilder#1674]
When there is no browser localStorage holding the theme information, the theme gets set incorrectly, and makes theme updates later impossible.

You can reproduce the error by removing the localStorage from the browser, or use incognito mode.

```
(index):71 Uncaught DOMException: Failed to execute 'add' on 'DOMTokenList': The token provided must not be empty.
    at https://book.kubebuilder.io/:71:28
(anonymous) @ (index):71
book.js:362 Uncaught DOMException: Failed to execute 'remove' on 'DOMTokenList': The token provided must not be empty.
    at set_theme (https://book.kubebuilder.io/book.js:362:24)
    at themes (https://book.kubebuilder.io/book.js:371:5)
    at https://book.kubebuilder.io/book.js:433:3
```

After this error, the theme selection would not work, and the sidebar control also stops functioning (though responsive view is handled correctly at reload of the page).

/kind documentation
/kind bug

**Comment by rytswd** [comment]
This looks to be fixed in the master branch, and we only need the new release to pick up the latest to book-v2 branch. Closing as there is no further action needed.
