### ISSUE TITLE
`make deploy` failed with nil error from kustomize

### ISSUE THREAD

**Issue by Skarlso** [kubernetes-sigs/kubebuilder#1926]
Nil error from kustomize.

Full trace:

```
➜  kubebuilder make deploy
/Users/skarlso/go/bin/controller-gen "crd:trivialVersions=true" rbac:roleName=manager-role webhook paths="./..." output:crd:artifacts:config=config/crd/bases
cd config/manager && kustomize edit set image controller=controller:latest
kustomize build config/default | kubectl apply -f -
panic: interface conversion: interface {} is string, not map[string]interface {}

goroutine 1 [running]:
sigs.k8s.io/kustomize/api/resmap.getNamespacesForRoleBinding(0xc0006adf40, 0x19)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/resmap/reswrangler.go:417 +0x352
sigs.k8s.io/kustomize/api/resmap.(*resWrangler).SubsetThatCouldBeReferencedByResource(0xc00034ebc0, 0xc0006adf40, 0xb, 0xc000687801)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/resmap/reswrangler.go:384 +0xdb
sigs.k8s.io/kustomize/api/internal/accumulator.(*nameReferenceTransformer).Transform(0xc000201f20, 0x555a060, 0xc00034ebc0, 0xc00034ebc0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/namereferencetransformer.go:85 +0x531
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).Transform(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/resaccumulator.go:138
sigs.k8s.io/kustomize/api/internal/accumulator.(*ResAccumulator).FixBackReferences(0xc00034eba0, 0xc00034eba0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/accumulator/resaccumulator.go:164 +0xbe
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).makeCustomizedResMap(0xc0001ff600, 0x0, 0x0, 0x5552100, 0x5fb6700)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/target/kusttarget.go:125 +0x7d
sigs.k8s.io/kustomize/api/internal/target.(*KustTarget).MakeCustomizedResMap(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/internal/target/kusttarget.go:106
sigs.k8s.io/kustomize/api/krusty.(*Kustomizer).Run(0xc001137d20, 0x7ffeefbff9c0, 0xe, 0x0, 0x0, 0x0, 0x0)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/sigs.k8s.io/kustomize/api@v0.7.0/krusty/kustomizer.go:77 +0x29b
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.(*Options).RunBuild(0xc0005060e0, 0x54fcfa0, 0xc000010018, 0x1, 0x0)
	/private/tmp/kustomize-20201210-91507-flrdla/kustomize/internal/commands/build/build.go:148 +0xb5
sigs.k8s.io/kustomize/kustomize/v3/internal/commands/build.NewCmdBuild.func1(0xc000215b80, 0xc0004b2db0, 0x1, 0x1, 0x0, 0x0)
	/private/tmp/kustomize-20201210-91507-flrdla/kustomize/internal/commands/build/build.go:70 +0xad
github.com/spf13/cobra.(*Command).execute(0xc000215b80, 0xc0004b2d80, 0x1, 0x1, 0xc000215b80, 0xc0004b2d80)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x47c
github.com/spf13/cobra.(*Command).ExecuteC(0xc000215600, 0x0, 0xffffffff, 0xc00009c058)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/private/tmp/kustomize-20201210-91507-flrdla/kustomize/main.go:19 +0x2a
```

Things to work.

I'm following the kubebuilder book. I'm at this section:
https://kubebuilder.io/cronjob-tutorial/running-webhook.html
I applied the mentioned changes, i.e.: uncommented the commented sections in that file.

What versions of software are you using?  Specifically, the following are often useful:

* go version
1.15.6
* kubebuilder version (`kubebuilder version`) and scaffolding version (check your `PROJECT` file)
```
➜  kubebuilder kubebuilder version
Version: version.Version{KubeBuilderVersion:"2.3.1", KubernetesVendor:"1.16.4", GitCommit:"8b53abeb4280186e494b726edf8f54ca7aa64a49", BuildDate:"2020-03-26T16:42:00Z", GoOs:"unknown", GoArch:"unknown"}
```
* controller-runtime version (check your `go.mod` file)
`sigs.k8s.io/controller-runtime v0.5.0`
* controller-tools version
no idea
* Kubernetes & kubectl versions (just run `kubectl version` against your API server)
Kubernetes is 1.16.15.

/kind bug

**Comment by Skarlso** [comment]
Here is the repository containing the code: https://github.com/Skarlso/kubebuilder-tutorial

**Comment by Skarlso** [comment]
Related to https://github.com/kubernetes-sigs/kustomize/issues/3340

Which means this might not be related to kubebuilder at all...

**Comment by Skarlso** [comment]
Ok, I'll have to revert kustomize version. Maybe that helps.

**Comment by Skarlso** [comment]
Actually tried the latest, 3.9.1.
And that *almost* worked.

```
The CustomResourceDefinition "cronjobs.batch.tutorial.kubebuilder.io" is invalid: spec.conversion.strategy: Invalid value: "Webhook": must be None if spec.preserveUnknownFields is true
make: *** [deploy] Error 1
```

**Comment by Skarlso** [comment]
But I guess that's the `The Bootstrapping Problem` outlined in the tutorial. So this issue can be closed then.

Thanks for the attention. :D

Also, there is now in image pull error, but I can see that someone already reported that one.
