### ISSUE TITLE
lint CI test's create-issue-action phase failing

### ISSUE THREAD

**Issue by mjlshen** [kubernetes-sigs/kubebuilder#3458]
### What broke? What's expected?

Recently, CI has been failing on the `Report Failure` phase with (there is also a golangci-lint failure that will be fixed in #3456):

```
Run nashmaniac/create-issue-action@v1.1
  with:
    title: 🐛 Lint failed for d9c14df9d84fafd08c9ec88441e9ce[2](https://github.com/kubernetes-sigs/kubebuilder/actions/runs/5263729808/jobs/9514184264#step:6:2)18ad6effa
    token: ***
    labels: kind/bug
    body: https://github.com/kubernetes-sigs/kubebuilder/actions/runs/526[3](https://github.com/kubernetes-sigs/kubebuilder/actions/runs/5263729808/jobs/9514184264#step:6:3)729808
/usr/bin/docker run --name ed866ed18fa6d26f6[4](https://github.com/kubernetes-sigs/kubebuilder/actions/runs/5263729808/jobs/9514184264#step:6:4)4993b[5](https://github.com/kubernetes-sigs/kubebuilder/actions/runs/5263729808/jobs/9514184264#step:6:5)c0ef[6](https://github.com/kubernetes-sigs/kubebuilder/actions/runs/5263729808/jobs/9514184264#step:6:6)14dc6653d_c2a[8](https://github.com/kubernetes-sigs/kubebuilder/actions/runs/5263729808/jobs/9514184264#step:6:9)01 --label ed866e --workdir /github/workspace --rm -e "INPUT_TITLE" -e "INPUT_TOKEN" -e "INPUT_LABELS" -e "INPUT_BODY" -e "INPUT_ASSIGNEES" -e "HOME" -e "GITHUB_JOB" -e "GITHUB_REF" -e "GITHUB_SHA" -e "GITHUB_REPOSITORY" -e "GITHUB_REPOSITORY_OWNER" -e "GITHUB_REPOSITORY_OWNER_ID" -e "GITHUB_RUN_ID" -e "GITHUB_RUN_NUMBER" -e "GITHUB_RETENTION_DAYS" -e "GITHUB_RUN_ATTEMPT" -e "GITHUB_REPOSITORY_ID" -e "GITHUB_ACTOR_ID" -e "GITHUB_ACTOR" -e "GITHUB_TRIGGERING_ACTOR" -e "GITHUB_WORKFLOW" -e "GITHUB_HEAD_REF" -e "GITHUB_BASE_REF" -e "GITHUB_EVENT_NAME" -e "GITHUB_SERVER_URL" -e "GITHUB_API_URL" -e "GITHUB_GRAPHQL_URL" -e "GITHUB_REF_NAME" -e "GITHUB_REF_PROTECTED" -e "GITHUB_REF_TYPE" -e "GITHUB_WORKFLOW_REF" -e "GITHUB_WORKFLOW_SHA" -e "GITHUB_WORKSPACE" -e "GITHUB_ACTION" -e "GITHUB_EVENT_PATH" -e "GITHUB_ACTION_REPOSITORY" -e "GITHUB_ACTION_REF" -e "GITHUB_PATH" -e "GITHUB_ENV" -e "GITHUB_STEP_SUMMARY" -e "GITHUB_STATE" -e "GITHUB_OUTPUT" -e "RUNNER_OS" -e "RUNNER_ARCH" -e "RUNNER_NAME" -e "RUNNER_TOOL_CACHE" -e "RUNNER_TEMP" -e "RUNNER_WORKSPACE" -e "ACTIONS_RUNTIME_URL" -e "ACTIONS_RUNTIME_TOKEN" -e "ACTIONS_CACHE_URL" -e GITHUB_ACTIONS=true -e CI=true -v "/var/run/docker.sock":"/var/run/docker.sock" -v "/home/runner/work/_temp/_github_home":"/github/home" -v "/home/runner/work/_temp/_github_workflow":"/github/workflow" -v "/home/runner/work/_temp/_runner_file_commands":"/github/file_commands" -v "/home/runner/work/kubebuilder/kubebuilder":"/github/workspace" ed866e:d18fa6d26f644993b5c0ef614dc6653d
Traceback (most recent call last):
  File "/script.py", line 2, in <module>
    import github
  File "/usr/local/lib/python3.11/site-packages/github/__init__.py", line 58, in <module>
    from github.MainClass import Github, GithubIntegration
  File "/usr/local/lib/python3.11/site-packages/github/MainClass.py", line 5[9](https://github.com/kubernetes-sigs/kubebuilder/actions/runs/5263729808/jobs/9514184264#step:6:10), in <module>
    import github.Event
  File "/usr/local/lib/python3.11/site-packages/github/Event.py", line 34, in <module>
    import github.NamedUser
  File "/usr/local/lib/python3.11/site-packages/github/NamedUser.py", line 46, in <module>
    import github.Organization
  File "/usr/local/lib/python3.11/site-packages/github/Organization.py", line 52, in <module>
    import github.Repository
  File "/usr/local/lib/python3.11/site-packages/github/Repository.py", line 93, in <module>
    from deprecated import deprecated
  File "/usr/local/lib/python3.11/site-packages/deprecated/__init__.py", line 13, in <module>
    from deprecated.classic import deprecated
  File "/usr/local/lib/python3.11/site-packages/deprecated/classic.py", line 15, in <module>
    import wrapt
  File "/usr/local/lib/python3.11/site-packages/wrapt/__init__.py", line [10](https://github.com/kubernetes-sigs/kubebuilder/actions/runs/5263729808/jobs/9514184264#step:6:11), in <module>
    from .decorators import (adapter_factory, AdapterFactory, decorator,
  File "/usr/local/lib/python3.[11](https://github.com/kubernetes-sigs/kubebuilder/actions/runs/5263729808/jobs/9514184264#step:6:12)/site-packages/wrapt/decorators.py", line 34, in <module>
    from inspect import ismethod, isclass, formatargspec
ImportError: cannot import name 'formatargspec' from 'inspect' (/usr/local/lib/python3.11/inspect.py)
```

This should be fixed by updating the corresponding GitHub action's dependencies according to https://github.com/GrahamDumpleton/wrapt/issues/196#issuecomment-1063798043. I've submitted a corresponding issue upstream to https://github.com/nashmaniac/create-issue-action/issues/12 and PR fix upstream and can pull it into Kubebuilder when it merges.

Alternatively, if it doesn't get looked at soon (the project looks slightly abandoned, we may want to consider a different GitHub action for this that's more actively maintained).

**Comment by camilamacedo86** [comment]
The job was removed.
@mjlshen thank you a lot for your help.
