### ISSUE TITLE
kubebuilder create api: Makefile:9: recipe for target 'test' failed

### ISSUE THREAD

**Issue by StianOvrevage** [kubernetes-sigs/kubebuilder#364]
I've been trying to scaffold a new project now for 2 days on 2 different machines both running Ubuntu on Windows Subsystem for Linux.

kubebuilder v1.0.0 darwin as per documentaton.

`go version go1.10 linux/amd64`

Clear the directory from previous failed attempts:
```
rm -rf *
```

Initialize
```
$ kubebuilder init ships
Run `dep ensure` to fetch dependencies (Recommended) [y/n]?
y
dep ensure

Running make...
make
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go all
CRD manifests generated under '/mnt/xx-api/config/crds'
RBAC manifests generated under '/mnt/xx-api/config/rbac'
go test ./pkg/... ./cmd/... -coverprofile cover.out
?       xx-api/pkg/apis   [no test files]
?       xx-api/pkg/controller     [no test files]
?       xx-api/cmd/manager        [no test files]
go build -o bin/manager xx-api/cmd/manager
Next: Define a resource with:
$ kubebuilder create api
```

Create
```
$ kubebuilder create api --group ships --kind Sloop --version v1beta1
Create Resource under pkg/apis [y/n]?
y
Create Controller under pkg/controller [y/n]?
y
Writing scaffold for you to edit...
pkg/apis/ships/v1beta1/sloop_types.go
pkg/apis/ships/v1beta1/sloop_types_test.go
pkg/controller/sloop/sloop_controller.go
pkg/controller/sloop/sloop_controller_test.go
Running make...
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go all
CRD manifests generated under '/mnt/xx-api/config/crds'
RBAC manifests generated under '/mnt/xx-api/config/rbac'
go test ./pkg/... ./cmd/... -coverprofile cover.out
?       xx-api/pkg/apis   [no test files]
?       xx-api/pkg/apis/ships     [no test files]
2018/08/27 19:20:13 timeout waiting for process etcd to start
FAIL   xx-api/pkg/apis/ships/v1beta1     20.297s
?       xx-api/pkg/controller     [no test files]
2018/08/27 19:20:13 timeout waiting for process etcd to start
FAIL    xx-api/pkg/controller/sloop       20.053s
?       xx-api/cmd/manager        [no test files]
Makefile:9: recipe for target 'test' failed
make: *** [test] Error 1
2018/08/27 19:20:13 exit status 2
```

**Comment by droot** [comment]
Looking at the failure, looks like it is not able to bring up etcd server. You mentioned that `Ubuntu on Windows Subsystem for Linux`, not sure if etcd binary shipped with Kubebuilder is compatible with that.

Can you run <path-to-kb>/bin/etcd and paste the output here ?

**Comment by StianOvrevage** [comment]
Sure:

```
$ which etcd
/usr/local/kubebuilder/bin/etcd
$ etcd
2018-08-27 23:27:59.477567 I | etcdmain: etcd Version: 3.3.0+git
2018-08-27 23:27:59.478436 I | etcdmain: Git SHA: Not provided (use ./build instead of go build)
2018-08-27 23:27:59.479114 I | etcdmain: Go Version: go1.10.1
2018-08-27 23:27:59.479771 I | etcdmain: Go OS/Arch: linux/amd64
2018-08-27 23:27:59.481074 I | etcdmain: setting maximum number of CPUs to 12, total number of available CPUs is 12
2018-08-27 23:27:59.481915 W | etcdmain: no data-dir provided, using default data-dir ./default.etcd
2018-08-27 23:27:59.705411 I | etcdserver: name = default
2018-08-27 23:27:59.705758 I | etcdserver: data dir = default.etcd
2018-08-27 23:27:59.706571 I | etcdserver: member dir = default.etcd/member
2018-08-27 23:27:59.707188 I | etcdserver: heartbeat = 100ms
2018-08-27 23:27:59.708393 I | etcdserver: election = 1000ms
2018-08-27 23:27:59.709048 I | etcdserver: snapshot count = 100000
2018-08-27 23:27:59.709958 I | etcdserver: advertise client URLs = http://localhost:2379
2018-08-27 23:27:59.710580 I | etcdserver: initial advertise peer URLs = http://localhost:2380
2018-08-27 23:27:59.713553 I | etcdserver: initial cluster = default=http://localhost:2380
2018-08-27 23:27:59.791295 I | wal: releasing file lock to rename "default.etcd/member/wal.tmp" to "default.etcd/member/wal"
2018-08-27 23:27:59.840983 I | etcdserver: starting member 8e9e05c52164694d in cluster cdf818194e3a8c32
2018-08-27 23:27:59.842554 I | raft: 8e9e05c52164694d became follower at term 0
2018-08-27 23:27:59.842729 I | raft: newRaft 8e9e05c52164694d [peers: [], term: 0, commit: 0, applied: 0, lastindex: 0, lastterm: 0]
2018-08-27 23:27:59.843940 I | raft: 8e9e05c52164694d became follower at term 1
panic: invalid page type: 0: 4

goroutine 1 [running]:
github.com/coreos/etcd/vendor/github.com/coreos/bbolt.(*Cursor).search(0xc420294420, 0x187b45c, 0x5, 0x5, 0x4)
        /go/src/github.com/coreos/etcd/vendor/github.com/coreos/bbolt/cursor.go:256 +0x388
github.com/coreos/etcd/vendor/github.com/coreos/bbolt.(*Cursor).seek(0xc420294420, 0x187b45c, 0x5, 0x5, 0x0, 0x0, 0xc420000180, 0x300000002, 0xc420000180, 0xc420294400, ...)
        /go/src/github.com/coreos/etcd/vendor/github.com/coreos/bbolt/cursor.go:159 +0xa5
github.com/coreos/etcd/vendor/github.com/coreos/bbolt.(*Bucket).CreateBucket(0xc42015a018, 0x187b45c, 0x5, 0x5, 0x1, 0xc4202662a0, 0xc420294510)
        /go/src/github.com/coreos/etcd/vendor/github.com/coreos/bbolt/bucket.go:165 +0xfa
github.com/coreos/etcd/vendor/github.com/coreos/bbolt.(*Tx).CreateBucket(0xc42015a000, 0x187b45c, 0x5, 0x5, 0x7fdf169a5ce0, 0x8, 0xaa)
        /go/src/github.com/coreos/etcd/vendor/github.com/coreos/bbolt/tx.go:108 +0x4f
github.com/coreos/etcd/mvcc/backend.(*batchTx).UnsafeCreateBucket(0xc42027f770, 0x187b45c, 0x5, 0x5)
        /go/src/github.com/coreos/etcd/mvcc/backend/batch_tx.go:48 +0x6b
github.com/coreos/etcd/lease.(*lessor).initAndRecover(0xc42028e000)
        /go/src/github.com/coreos/etcd/lease/lessor.go:586 +0xab
github.com/coreos/etcd/lease.newLessor(0x11446c0, 0xc42026a770, 0x2, 0xc42025a2a0)
        /go/src/github.com/coreos/etcd/lease/lessor.go:171 +0x1be
github.com/coreos/etcd/lease.NewLessor(0x11446c0, 0xc42026a770, 0x2, 0x18be5a0, 0xc420266300)
        /go/src/github.com/coreos/etcd/lease/lessor.go:156 +0x3f
github.com/coreos/etcd/etcdserver.NewServer(0x103466b, 0x7, 0x0, 0x0, 0x0, 0x0, 0xc42028eb00, 0x1, 0x1, 0xc42028e980, ...)
        /go/src/github.com/coreos/etcd/etcdserver/server.go:520 +0x18b4
github.com/coreos/etcd/embed.StartEtcd(0xc420324000, 0xc42033a000, 0x0, 0x0)
        /go/src/github.com/coreos/etcd/embed/etcd.go:198 +0x885
github.com/coreos/etcd/etcdmain.startEtcd(0xc420324000, 0x10317b0, 0x3, 0x1032701, 0x5)
        /go/src/github.com/coreos/etcd/etcdmain/etcd.go:293 +0x40
github.com/coreos/etcd/etcdmain.startEtcdOrProxyV2()
        /go/src/github.com/coreos/etcd/etcdmain/etcd.go:161 +0x2f0b
github.com/coreos/etcd/etcdmain.Main()
        /go/src/github.com/coreos/etcd/etcdmain/main.go:47 +0x3f
main.main()
        /go/src/github.com/coreos/etcd/main.go:28 +0x20
```

**Comment by droot** [comment]
This confirms the `etcd` binary is not compatible with your env. You can build the two binaries (kube-apiserver, etcd) for your system and replace it manually under `/usr/local/kubebuilder/bin/` and retry.

Also, note that your project and code files are in good shape, its the test which are failing because tests bring up etcd and kube-apiserver to run against.

**Comment by StianOvrevage** [comment]
Thanks for your reply. I (think I) tracked down the error to an unresolved issue with Windows Subsystem for Linux and BoltDB.

Is there a way to disable the tests or the etcd part to avoid creating these errors?

**Comment by droot** [comment]
You can remove the `test` target as prerequisite in other targets in the project's Makefile.

Closing this issue since it doesn't require a fix in Kubebuilder.

**Comment by axsaucedo** [comment]
@StianOvrevage could you link to what unresolved issue you are referring to? Thanks!
