### ISSUE TITLE
Fix race condition in generated controller tests 

### ISSUE THREAD

**Issue by droot** [kubernetes-sigs/kubebuilder#416]
Travis reported the following failure. Its a race condition which happens when `t.Errorf` or `t.Fatalf` is being called after the test has exited. This can simply be fixed by waiting for manager to finish before we return from the Test fn (more details about the fix in the PR)

```sh
panic: Fail in goroutine after  has completed
goroutine 281 [running]:
testing.(*common).Fail(0xc420466000)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:509 +0x134
testing.(*common).Fail(0xc4204660f0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:503 +0x98
testing.(*common).FailNow(0xc4204660f0)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:531 +0x2b
testing.(*common).Fatalf(0xc4204660f0, 0x127b039, 0x3, 0xc420316f50, 0x1, 0x1)
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/testing/testing.go:597 +0x83
github.com/kubernetes-sigs/kubebuilder-test/vendor/github.com/onsi/gomega/internal/testingtsupport.BuildTestingTGomegaFailWrapper.func1(0xc4201702a0, 0xd8, 0xc4200404d8, 0x1, 0x1)
	/home/travis/gopath/src/github.com/kubernetes-sigs/kubebuilder-test/vendor/github.com/onsi/gomega/internal/testingtsupport/testing_t_support.go:30 +0x2c4
github.com/kubernetes-sigs/kubebuilder-test/vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc4205425c0, 0x138ce20, 0x1c42ef0, 0x0, 0x0, 0x0, 0x0, 0x1c42ef0)
	/home/travis/gopath/src/github.com/kubernetes-sigs/kubebuilder-test/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:75 +0x20e
github.com/kubernetes-sigs/kubebuilder-test/vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).NotTo(0xc4205425c0, 0x138ce20, 0x1c42ef0, 0x0, 0x0, 0x0, 0x139d320)
	/home/travis/gopath/src/github.com/kubernetes-sigs/kubebuilder-test/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:48 +0xc9
github.com/kubernetes-sigs/kubebuilder-test/pkg/controller/deployment.StartTestManager.func1(0xc42028d260, 0x13a9180, 0xc42010fec0, 0xc4203bd140)
	/home/travis/gopath/src/github.com/kubernetes-sigs/kubebuilder-test/pkg/controller/deployment/deployment_controller_suite_test.go:67 +0xda
created by github.com/kubernetes-sigs/kubebuilder-test/pkg/controller/deployment.StartTestManager
	/home/travis/gopath/src/github.com/kubernetes-sigs/kubebuilder-test/pkg/controller/deployment/deployment_controller_suite_test.go:66 +0x7f
FAIL	github.com/kubernetes-sigs/kubebuilder-test/pkg/controller/deployment	9.529s
?   	github.com/kubernetes-sigs/kubebuilder-test/cmd/manager	[no test files]
make: *** [test] Error 1
2018/10/02 07:42:26 exit status 2
```

**Comment by droot** [comment]
similar issue https://github.com/golang/go/issues/15976

**Comment by droot** [comment]
If you are running in to this issue. Here are the steps to fix in your tests:

Edit pkg/controller/<kind>/<kind>_controller_suite_test.go and change the `StartTestManager` fn.
```Go
// StartTestManager adds recFn
func StartTestManager(mgr manager.Manager, g *gomega.GomegaWithT) (chan struct{}, sync.WaitGroup) {
        stop := make(chan struct{})
        wg := sync.WaitGroup{}
        go func() {
                wg.Add(1)
                g.Expect(mgr.Start(stop)).NotTo(gomega.HaveOccurred())
                wg.Done()
        }()
        return stop, wg
}
```

Edit pkg/controller/<kind>/<kind>_controller_test.go and edit `TestReconcile` function and replace the first `defer` statement with the following code (look for an actual diff in the PR linked above):

```Go
        stopMgr, mgrStopped := StartTestManager(mgr, g)

        defer func() {
                close(stopMgr)
                mgrStopped.Wait()
        }()
```

**Comment by kierendavies** [comment]
`wg.Add(1)` should be called before the goroutine. Otherwise, if `TestReconcile` has no tests after that `defer`, then it's possible that the `defer` finishes before the `StartTestManager` goroutine executes, and the panic happens like before. ([Relevant docs](https://golang.org/pkg/sync/#WaitGroup.Add).)
