### ISSUE TITLE
quick-start.md: kubebuilder init runtime error

### ISSUE THREAD

**Issue by songleo** [kubernetes-sigs/kubebuilder#800]
/kind bug

When following quick-start.md I get the following error when running `kubebuilder init --domain my.domain`:

```
$ kubebuilder init --domain my.domain
Run `dep ensure` to fetch dependencies (Recommended) [y/n]?
y
dep ensure
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/golang/dep/gps.(*solver).findValidVersion(0xc0005c4400, 0xc004ef3220, 0xc004301c00, 0x1f, 0x1f, 0x0, 0xc004301c00)
	/Users/travis/gopath/src/github.com/golang/dep/gps/solver.go:945 +0x4cc
github.com/golang/dep/gps.(*solver).backtrack(0xc0005c4400, 0xadbda0, 0xc0000a6060, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/golang/dep/gps/solver.go:1079 +0xbdc
github.com/golang/dep/gps.(*solver).solve(0xc0005c4400, 0xadbda0, 0xc0000a6060, 0x5, 0xc0002d4498, 0xc0000eb548)
	/Users/travis/gopath/src/github.com/golang/dep/gps/solver.go:510 +0x872
github.com/golang/dep/gps.(*solver).Solve(0xc0005c4400, 0xadbda0, 0xc0000a6060, 0xeb0a88, 0xc000022113, 0x9, 0xc000183da0)
	/Users/travis/gopath/src/github.com/golang/dep/gps/solver.go:440 +0x1eb
main.(*ensureCommand).runDefault(0xc00016d676, 0xc0000d8880, 0xc00009d680, 0x0, 0x0, 0xc0000d5200, 0xae3c20, 0xc000228300, 0xc000022104, 0x18, ...)
	/Users/travis/gopath/src/github.com/golang/dep/cmd/dep/ensure.go:281 +0x3fb
main.(*ensureCommand).Run(0xc00016d676, 0xc0000d8880, 0xc00009d680, 0x0, 0x0, 0x0, 0x0)
	/Users/travis/gopath/src/github.com/golang/dep/cmd/dep/ensure.go:218 +0x80e
main.(*Config).Run(0xc0000b4ea0, 0x0)
	/Users/travis/gopath/src/github.com/golang/dep/cmd/dep/main.go:212 +0x111c
main.main()
	/Users/travis/gopath/src/github.com/golang/dep/cmd/dep/main.go:84 +0x636
2019/06/18 23:21:50 exit status 2
```

when I remove the old project and run `kubebuilder init --domain my.domain` again,  everything is ok. 

```
$ kubebuilder init --domain my.domain
Run `dep ensure` to fetch dependencies (Recommended) [y/n]?
y
dep ensure
Running make...
make
go generate ./pkg/... ./cmd/...
go fmt ./pkg/... ./cmd/...
go vet ./pkg/... ./cmd/...
go run vendor/sigs.k8s.io/controller-tools/cmd/controller-gen/main.go all
CRD manifests generated under '/share/git/src/guestbook/config/crds'
RBAC manifests generated under '/share/git/src/guestbook/config/rbac'
webhook manifests generated under '/share/git/src/guestbook/config/webhook' directory
go test ./pkg/... ./cmd/... -coverprofile cover.out
?   	guestbook/pkg/apis	[no test files]
?   	guestbook/pkg/controller	[no test files]
?   	guestbook/pkg/webhook	[no test files]
?   	guestbook/cmd/manager	[no test files]
go build -o bin/manager guestbook/cmd/manager
Next: Define a resource with:
$ kubebuilder create api
```

OS info:

```
root@ssli-dev:pkg$ cat /etc/issue
Ubuntu 16.04.6 LTS \n \l

root@ssli-dev:pkg$ go version
go version go1.12.5 linux/amd64
root@ssli-dev:pkg$ kind version
v0.3.0
root@ssli-dev:pkg$ docker version
Client:
 Version:           18.09.2
 API version:       1.39
 Go version:        go1.10.4
 Git commit:        6247962
 Built:             Tue Feb 26 23:56:24 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.2
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.10.4
  Git commit:       6247962
  Built:            Tue Feb 12 22:47:29 2019
  OS/Arch:          linux/amd64
  Experimental:     false
root@ssli-dev:pkg$ kustomize version
Version: {KustomizeVersion:v2.0.4-kubebuilder-special-edition GitCommit:f9c631e9eec7a2d6e46eb9e1bf5122f68b97d12d BuildDate:1970-01-01T00:00:00Z GoOs:linux GoArch:amd64}
root@ssli-dev:pkg$ kubebuilder version
Version: version.Version{KubeBuilderVersion:"1.0.8", KubernetesVendor:"1.13.1", GitCommit:"1adf50ed107f5042d7472ba5ab50d5e1d357169d", BuildDate:"2019-01-25T23:14:29Z", GoOs:"unknown", GoArch:"unknown"}
```

**Comment by mengqiy** [comment]
What version of kubebuilder are you using?
It seems you are using an old version, since it uses `dep ensure`.
Newer version uses go modules by default.

**Comment by mengqiy** [comment]
expected output looks like:
```
$ kubebuilder init --domain my.domain
go mod tidy
Running make...
make
/usr/local/google/home/mengqiy/work/golang/src/sigs.k8s.io/controller-tools/bin/controller-gen object:headerFile=./hack/boilerplate.go.txt paths=./api/...
go fmt ./...
go vet ./...
go build -o bin/manager main.go
Next: Define a resource with:
$ kubebuilder create api
```

**Comment by songleo** [comment]
@mengqiy Thanks you for your help.
